services:
  docmost:
    container_name: docmost
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "${APP_URL}" #"http://localhost:3000"
      APP_SECRET: "${APP_SECRET}"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@postgres:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "${PORT}:3000"
    restart: unless-stopped
    volumes:
      - ${MNT}:/app/data/storage
    labels:
      caddy: ${APP_URL}
      caddy.reverse_proxy: "{{ upstreams 3000 }}"
      caddy.reverse_proxy.header_up_0: "Connection {>Connection}"
      caddy.reverse_proxy.header_up_1: "Upgrade {>Upgrade}"
    #networks:
      #- default
      #- tinyauth_net

  db:
    container_name: docmost-db
    hostname: postgres
    image: postgres:18
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ${MNT}/db:/var/lib/postgresql

  redis:
    container_name: docmost-redis
    hostname: redis
    image: redis:8
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    volumes:
      - ${MNT}/redis:/data

networks:
  default:
    internal: true
    name: docmost_network
    #ipam:
      #config:
       #- subnet: 172.25.6.0/29
         #gateway: 172.25.6.1
  #tinyauth_net:
    #external: true
