services:
  gatus:
    container_name: gatus
    image: ghcr.io/thackmaster/homelab/gatus:latest
    restart: unless-stopped
    ports:
      - ${PORT}:8080
    environment:
    - SLACK_URL=${SLACK_URL}
    volumes:
      - ${MNT}:/config
      - ./config.template.yml:/app/config.template.yml:ro
      - ./entrypoint.sh:/app/entrypoint.sh:ro
