services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      - "${PORT_HTTP}:80/tcp" # HTTP WEB ACCESS
      - "${PORT_HTTPS}:443/tcp" # HTTPS WEB ACCESS
    environment:
      TZ: 'America/Denver'
      FTLCONF_webserver_api_password: '${WEB_PASS}'
      #FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: 9.9.9.9;149.112.112.112;9.9.9.11;149.112.112.11;1.1.1.1;1.0.0.1;208.67.222.222;208.67.220.220
      PIHOLE_UID: ${UID}
      PIHOLE_GID: ${GID}
    volumes:
      - '${MNT}/pihole:/etc/pihole'
      - '${MNT}:/etc/dnsmasq.d'
    restart: unless-stopped
