services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      # - "67:67/udp" DHCP
      - "${PORT}:80/tcp" # WEB ACCESS
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: '${WEB_PASS}'
    volumes:
      - '${MNT}/pihole:/etc/pihole'
      - '${MNT}:/etc/dnsmasq.d'
    # cap_add:
      # - NET_ADMIN Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped