services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      # - "67:67/udp" DHCP
      - "${PORT_HTTP}:80/tcp" # HTTP WEB ACCESS
      - "${PORT_HTTPS}:443/tcp" # HTTPS WEB ACCESS
    environment:
      TZ: 'America/Denver'
      FTLCONF_webserver_api_password: '${WEB_PASS}'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - '${MNT}/pihole:/etc/pihole'
      #- '${MNT}:/etc/dnsmasq.d'
    # cap_add:
      # - NET_ADMIN Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
