services:
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:v5
    hostname: tinyauth
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TINYAUTH_APPURL=${APP_URL}
      - TINYAUTH_AUTH_USERS=${USERS}
      - TINYAUTH_LDAP_ADDRESS=ldap://lldap:3890
      - TINYAUTH_LDAP_BINDDN=${LDAP_DN}
      - TINYAUTH_LDAP_BINDPASSWORD=${LDAP_BIND_PASS}
      - TINYAUTH_LDAP_BASEDN=${LDAP_BASE_DN}
      - TINYAUTH_LDAP_SEARCHFILTER=(uid=%s)
      - TINYAUTH_LDAP_INSECURE=true
    networks:
      - default
      - auth_net
      - caddy
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      labels:
        caddy: ${APP_URL}
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.tls: "internal"

networks:
  default:
    name: tinyauth_net
    driver: overlay
    internal: true
  auth_net:
    external: true
  caddy:
    name: caddy
    external: true
