all:
  children:
    homelab:
      children:
        debian:
          hosts:
            plexums.lan:
              ansible_host: 172.16.10.4
            pipsqueak.lan:
              ansible_host: 172.16.10.5
            optiplex.lan:
              ansible_host: 172.16.10.6
        redhat:
          hosts:
            redhat1.lan:
              ansible_host: 172.16.10.3
    azure:
      hosts:
        100.126.119.92:
          ansible_user: user
          ansible_ssh_private_key_file: /path/to/key-file.pem
          ansible_ask_pass: false