homelab:
  hosts:
    debby-ann.lan:
      ansible_host: 172.16.10.3
    plexums.lan:
      ansible_host: 172.16.10.4
    pipsqueak.lan:
      ansible_host: 172.16.10.5
    optiplex.lan:
      ansible_host: 172.16.10.6
azure:
  hosts:
    100.126.119.92:
      ansible_user: user
      ansible_ssh_private_key_file: /path/to/key-file.pem
      ansible_ask_pass: false