- name: Update Portainer
  hosts: all
  become: true
  tasks:
    
    - name: Pull latest image
      docker_image:
        name: portainer/portainer-ce
        source: pull
    
    - name: Stop existing portainer container
      docker_container:
        name: portainer
        state: stopped
        force_kill: false
      ignore_errors: true
    
    - name: Remove portainer container
      docker_container:
        name: portainer
        state: absent
      ignore_errors: true
    
    - name: Create portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        restart_policy: always
        ports: 
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data