- name: Show whoami
  hosts: all
  become: true
  tasks:
    - name: whoami command
      command: whoami
      register: whoami_output
    - name: output whoami
      debug:
        var: whoami_output

- name: Run apt-get update on remote hosts
  hosts: all
  become: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade
      apt:
        upgrade: yes
    - name: Autoremove
      apt:
        autoremove: yes
