- name: Run apt-get update on remote hosts
  hosts: all
  become: true
  tasks:

    - name: Update packages (apt)
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
        autoremove: true
        clean: true
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Update packages (dnf/yum)
      block:

        - name: Update packages (dnf/yum)
          yum:
            name: '*'
            state: latest

        - name: Clean up packages (dnf/yum)
          yum:
            autoremove: yes

      when: ansible_distribution in ["Fedora", "CentOS", "RedHat"]

    - name: Remove hanging Docker artifacts (apt)
      community.docker.docker_prune:
        containers: false
        images: true
        networks: true
        volumes: false
        builder_cache: true
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Remove hanging Docker artifacts (dnf/yum)
      block:

        - name: Remove hanging Docker images (dnf/yum)
          command: docker image prune -f

        - name: Remove hanging Docker networks (dnf/yum)
          command: docker network prune -f

      when: ansible_distribution in ["Fedora", "CentOS", "RedHat"]

    - name: Check for reboot requirement
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Prompt for reboot (if necessary)
      pause:
        prompt: "Press ENTER to reboot {{ inventory_hostname }} now, or Ctrl+C to abort."
      when: reboot_required_file.stat.exists

    - name: Reboot (if necessary)
      reboot:
        msg: "Reboot initiated by Ansible"
        test_command: "logger '[ansible]: system was rebooted from Ansible after kernel upgrade'"
      when: reboot_required_file.stat.exists
