services:
  postgres:
    container_name: mattermost-db
    image: postgres:16-alpine
    restart: unless-stopped
    #security_opt:
      #- no-new-privileges:true
    #pids_limit: 100
    #read_only: true
    #tmpfs:
      #- /tmp
      #- /var/run/postgresql
    volumes:
      - ${MNT}/db:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  mattermost:
    container_name: mattermost
    depends_on:
      - postgres
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    #security_opt:
      #- no-new-privileges:true
    #pids_limit: 200
    #tmpfs:
      #- /tmp
    volumes:
      - ${MNT}/config:/mattermost/config:rw
      - ${MNT}/data:/mattermost/data:rw
      - ${MNT}/logs:/mattermost/logs:rw
      - ${MNT}/plugins:/mattermost/plugins:rw
      - ${MNT}/client-plugins:/mattermost/client/plugins:rw
      - ${MNT}/bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      - TZ=${TZ}
      - MM_SERVICESETTINGS_SITEURL=https://${DOMAIN}
      - MM_SQLSETTINGS_DRIVERNAME=${SQL_DRIVERNAME}
      - MM_SQLSETTINGS_DATASOURCE=${SQL_DATASOURCE}
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
    ports:
      - 8065:8065

networks:
  default:
      name: mattermost_network
      external: false
      ipam:
          config:
            - subnet: 172.20.8.0/29
              gateway: 172.20.8.1
