services:
  uptime-kuma:
    image: louislam/uptime-kuma:${VERSION}
    container_name: uptime-kuma
    ports:
      - ${PORT}:3001
    volumes:
    volumes:
      type: volume
        source: nfs-config
        target: /app/data
        volume:
          nocopy: true
          subpath: uptime-kuma

volumes:
  nfs-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NAS},rw,nolock,soft,nfsvers=4"
      device: ":${MNT_NAS}"
