services:

  bazarr: #subtitles
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${MNT_CONFIG}/bazarr:/config
      - nfs-media:/media
      - type: volume
        source: nfs-backups
        target: /config/backup
        volume:
          nocopy: true
          subpath: bazarr
    networks:
      default:
        aliases:
          - bazarr.local
    ports:
      - ${BAZARR_PORT:-6767}:6767
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE}
  
  prowlarr: #overview management
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${MNT_CONFIG}/prowlarr:/config
      - nfs-media:/media
      - type: volume
        source: nfs-backups
        target: /config/Backups
        volume:
          nocopy: true
          subpath: prowlarr
    networks:
      default:
        aliases:
          - prowlarr.local
    ports:
      - ${PROWLARR_PORT:-9696}:9696
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE}
  
  radarr: #movies
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${MNT_CONFIG}/radarr:/config
      - nfs-media:/media
      - type: volume
        source: nfs-backups
        target: /config/Backups
        volume:
          nocopy: true
          subpath: radarr
    networks:
      default:
        aliases:
          - radarr.local
    ports:
      - ${RADARR_PORT:-7878}:7878
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE}
      endpoint_mode: vip
  
  sonarr: #tv shows
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${MNT_CONFIG}/sonarr:/config
      - nfs-media:/media
      - type: volume
        source: nfs-backups
        target: /config/Backups
        volume:
          nocopy: true
          subpath: sonarr
    networks:
      default:
        aliases:
          - sonarr.local
    ports:
      - ${SONARR_PORT:-8989}:8989
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE}
      endpoint_mode: vip

  tautulli: #plex monitor
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
    volumes:
      - ${MNT_CONFIG}/tautulli/:/config
      - type: volume
        source: nfs-backups
        target: /config/backups
        volume:
          nocopy: true
          subpath: tautulli
    networks:
      default:
        aliases:
          - tautulli.local
    ports:
      - ${TAUTULLI_PORT:-8181}:8181
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE}
      endpoint_mode: vip
  
  #lidarr: #music. NOT IN USE
    #hostname: lidarr
    #image: lscr.io/linuxserver/lidarr:latest
    #container_name: lidarr
    #environment:
      #- PUID=${UID}
      #- PGID=${GID}
      #- TZ=${TZ}
    #volumes:
      #- ${MNT_CONFIG}/lidarr:/config:rw
      #- ${MNT_MUSIC}:/music:rw #optional
    #ports:
      #- ${LIDARR_PORT}:8686
    #restart: unless-stopped

  #readarr: #ebooks. NOT IN USE
    #hostname: readarr
    #image: lscr.io/linuxserver/readarr:develop
    #container_name: readarr
    #environment:
      #- PUID=${UID}
      #- PGID=${GID}
      #- TZ=${TZ}
    #volumes:
      #- ${MNT_CONFIG}/readarr:/config:rw
      #- ${MNT_BOOKS}:/books:rw #optional
    #ports:
      #- ${READARR_PORT}:8787
    #restart: unless-stopped

################
# REQUEST SITE #
################
  seerr: #requests
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      #- PORT=5055 #optional
    ports:
      - ${SEERR_PORT}:5055
    volumes:
      - type: volume
        source: nfs-ext-config
        target: /app/config
        volume:
          nocopy: true
          subpath: sonarr
    restart: unless-stopped
    networks:
      - default
      - caddy
    deploy:
      labels:
        caddy: ${REQUEST_URL}
        caddy.reverse_proxy: "{{ upstreams 5055 }}"

###################
# HELPER SERVICES #
###################

  kometa:
    image: kometateam/kometa:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - KOMETA_RUN=${KOMETA_RUN} #run immediately
      - KOMETA_TIMES=05:00|17:00
    volumes:
      - type: volume
        source: nfs-ext-config
        target: /config
        volume:
          nocopy: true
          subpath: kometa
   
  maintainerr:
    image: maintainerr/maintainerr:latest
    user: ${UID}:${GID}
    environment:
      - TZ=${TZ}
    volumes:
      - type: volume
        source: nfs-ext-config
        target: /opt/data
        volume:
          nocopy: true
          subpath: maintainerr
    networks:
      default:
        aliases:
          - maintainerr.local
    ports:
      - ${MAINTAINERR_PORT:-6246}:6246
    dns:
      - 127.0.0.11
      - 172.16.1.10
      - 172.16.1.3

  # tdarr: #conversions
    # hostname: tdarr
    # container_name: tdarr-server
    # image: ghcr.io/haveagitgat/tdarr:latest
    # restart: unless-stopped
    # network_mode: bridge
    # ports:
      # - ${TDARR_PORT}:8265 # webUI port
      # - 8266:8266 # server port
      # - 8267:8267 # Internal node port
      # - 8268:8268 # Example extra node port
    # environment:
      # - TZ=${TZ}
      # - PUID=${UID}
      # - PGID=${GID}
      # - UMASK_SET=002
      # - serverIP=
      # - serverPort=8266
      # - webUIPort=8265
      # - internalNode=true
      # - nodeID=MyInternalNode
    # volumes:
      # - ${MNT_CONFIG}/tdarr/app/server:/app/server
      # - ${MNT_CONFIG}/tdarr/app/configs:/app/configs
      # - ${MNT_CONFIG}/tdarr/app/logs:/app/logs
      # - ${MNT_MEDIA}:/media
      # - ${MNT_CONFIG}/tdarr/temp:/temp

####################
# DOWNLOAD CLIENTS #
####################
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - WEBUI_PORT=${QBITTORRENT_PORT}
      - TZ=${TZ}
    networks:
      default:
        aliases:
          - qbittorrent.local
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
    volumes:
      - type: volume
        source: nfs-ext-config
        target: /config
        volume:
          nocopy: true
          subpath: qbittorrent
      - type: volume
        source: nfs-media
        target: /downloads
        volume:
          nocopy: true
          subpath: Downloads

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - HTTP_PROXY=http://gluetun:8888
      - HTTPS_PROXY=http://gluetun:8888
    networks:
      default:
        aliases:
          - sabnzbd.local
    ports:
      - ${SABNZBD_PORT:-8080}:8080
    volumes:
      - type: volume
        source: nfs-ext-config
        target: /config
        volume:
          nocopy: true
          subpath: sabnzbd
      - type: volume
        source: nfs-media
        target: /downloads
        volume:
          nocopy: true
          subpath: Downloads

#######
# VPN #
#######
  gluetun:
    hostname: gluetun
    image: qmcgaw/gluetun:latest
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${GLUETUN_PORT:-8000}:8000 # Control endpoint
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - type: volume
        source: nfs-ext-config
        target: /gluetun
        volume:
          nocopy: true
          subpath: gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASS}
      # Wireguard:
      #- WIREGUARD_PRIVATE_KEY=
      #- WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=${TZ}
      - SERVER_COUNTRIES=United States
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      - BLOCK_MALICIOUS=off
      - DNS_UNBLOCK_HOSTNAMES=${UNBLOCK_URLS}
      - DNS_UPSTREAM_RESOLVERS=${DNS_UPSTREAM_RESOLVERS:-quad9,cloudflare}
      - DNS_CACHING=off
      - HEALTH_TARGET_ADDRESSES=${GLUETUN_HEALTH_PING:-9.9.9.9}
      - HTTPPROXY=on
      - HTTPPROXY_PORT=8888

volumes:
  nfs-media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NAS_IP},rw,nolock,soft,nfsvers=4"
      device: ":${MNT_MEDIA}"
  nfs-backups:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NAS_IP},rw,nolock,soft,nfsvers=4"
      device: ":${MNT_BACKUPS}"
  nfs-ext-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NAS_IP},rw,nolock,soft,nfsvers=4"
      device: ":${MNT_EXT_CONFIG}"

networks:
  default:
    driver: overlay
    name: arr_network
    internal: false
    attachable: true
  caddy:
    name: caddy
    external: true
